### ISSUE TITLE
Minor fixes in the Guidelines

### ISSUE THREAD

**Issue by rdinizcal** [ros-rvft/ros-rvft.github.io#6]
### CI2. 
  - [x] two git annotations without link

### CI3. 
  - [x] two git annotations without link
  - [x] broken list
  - [x] broken listing (missing environemtn)

### CD1. 
 - [x] one git annotation without link (lesunb/bsn)

### CD2. 
  - [x] two git annotation without link
  - [x] wiki annotation without link

### I1. 
 - [x] five git annotations without link
 - [x] Listing 1 is broken
 - [x] ((lifecycle_talker) )  os weird

### I2.
 - [x] git annotations without link.
 - [x] master api.py without link
 - [x] ROSMoni- toring

### I3.
 - [x] git annotations without link
 - [x] Listing is broken
 - [x] $ ros2_fuzzer .py service example_interfaces / AddTwoInts add_two_ints. is missing syntactical highlighting

### I4.
 - [x] Listing 1 is broken
 - [x] Listing 2 is broken

### PE2.
 - [x] git annotations without link
 - [x] doi without link

### SDB1.
 - [x] weird syntax "http: (patterns),"
 - [x] Listing 1 looks broken
 - [x] missing git links
 - [x] ref 5 is in different letter from others

### SDB2.
 - [x] missing git links
 - [x] Listing 1 is broken

### SBD3.
 - [x] missing git links
 - [x] listing 1 is broken
 - [x] listing 2 is broken

### MTA1.
 - [x] missing git links
 - [x] weird syntax: "a href="https://github.com/jr-robotics/ROSPenTo">(RosPenTo)"

### MTA2. 
 - [x] missing git links

### SE1.
 - [x] missing links (git and web)

### SE2.
 - [x] missing links

### AR1.
 - [x] missing links
 - [x] weird syntax: "Multi- robot diagnosis: Morais et al. [5], promotes " 

### AR2.
 - [x] missing links
 - [x] weird syntax: "Motion- Planning plugin"

**Comment by SchiopuMatei** [comment]
Implemented
